services:
#  grunt_utils_filerev.eventlistener.filerevpackage:
#    class: Utils\GruntBundle\Eventlistener\HttpKernel\FilerevPackageInjector
#    scope: request
#    arguments: [@service_container]
#    tags:
#      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  grunt.filerev.templating.asset.path_package:
    public: false
    class: Utils\GruntBundle\Templating\Asset\PathPackage
    arguments: [@request,"","","",""]
    scope: request

  grunt.filerev.templating.asset.url_package:
      public: false
      class: Utils\GruntBundle\Templating\Asset\UrlPackage
      arguments: ["","","","",""]