imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: configs/ }
    - { resource: services/ }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    title: House Of Agile
    from_address: jc@houseofagile.com
    office_address: contact@houseofagile.com
framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        title: %title%
        social_networks:
            linkedin: https://www.linkedin.com/company/5380482
            twitter: https://twitter.com/House_of_Agile
        application_name: %application_name%

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    auth_mode:  %mailer_auth_mode%
    encryption: %mailer_encryption%
    spool:     { type: memory }
